const mongoose = require("mongoose");

const AlimentoSchema = new mongoose.Schema({
  ID: { type: Number, unique: true, required: true },
  Nome: { type: String, required: true },
  Categoria: { type: String, required: true },
  "Unità di riferimento": { type: String, required: true },
  "Energia, kilojoules (kJ)": { type: Number, required: true },
  "Energia, calorie (kcal)": { type: Number, required: true },
  "Lipidi, totali (g)": { type: String, required: true },
  "Acidi grassi, saturi (g)": { type: String, required: true },
  "Acidi grassi, monoinsaturi (g)": { type: String, required: true },
  "Acidi grassi, polinsaturi (g)": { type: String, required: true },
  "Colesterolo (mg)": { type: String, required: true },
  "Glucidi, disponibili (g)": { type: String, required: true },
  "Zuccheri (g)": { type: String, required: true },
  "Amido (g)": { type: String, required: true },
  "Fibra alimentare (g)": { type: String, required: true },
  "Proteine (g)": { type: String, required: true },
  "Sale (NaCl) (g)": { type: String, required: true },
  "Alcool (g)": { type: String, required: true },
  "Acqua (g)": { type: String, required: true },
  "Attività di vitamina A, RE (µg-RE)": { type: String, required: true },
  "Attività di vitamina A, RAE (µg-RE)": { type: String, required: true },
  "Attività di beta-carotene (µg-BCE)": { type: String, required: true },
  "Beta-carotene (µg)": { type: String, required: true },
  "Vitamina B1 (tiamina) (mg)": { type: String, required: true },
  "Vitamina B2 (riboflavina) (mg)": { type: String, required: true },
  "Vitamina B6 (piridossina) (mg)": { type: String, required: true },
  "Vitamina B12 (cobalamina) (µg)": { type: String, required: true },
  "Niacina (mg)": { type: String, required: true },
  "Folati (µg)": { type: String, required: true },
  "Acido pantotenico (mg)": { type: String, required: true },
  "Vitamina C (acido ascorbico) (mg)": { type: String, required: true },
  "Vitamina D (calciferolo) (µg)": { type: String, required: true },
  "Vitamina E (α-tocoferolo) (mg)": { type: String, required: true },
  "Potassio (K) (mg)": { type: String, required: true },
  "Sodio (Na) (mg)": { type: String, required: true },
  "Cloro (Cl) (mg)": { type: String, required: true },
  "Calcio (Ca) (mg)": { type: String, required: true },
  "Magnesio (Mg) (mg)": { type: String, required: true },
  "Fosforo (P) (mg)": { type: String, required: true },
  "Ferro (Fe) (mg)": { type: String, required: true },
  "Iodio (I) (µg)": { type: String, required: true },
  "Zinco (Zn)  (mg)": { type: String, required: true },
  "Selenio (Se) (µg)": { type: String, required: true },
});

module.exports = mongoose.model("Alimento", AlimentoSchema, "alimentiSt");
